from summarize.modules.coverage_matrix_attention.coverage_matrix_attention import CoverageMatrixAttention
from summarize.modules.coverage_matrix_attention.matrix_attention_wrapper import MatrixAttentionWrapper
from summarize.modules.coverage_matrix_attention.mlp import MLPCoverageAttention
